Repository CMSgov/bluebutton-web-server, pull requests merged in 2021-05, with the labels that each got.

#912 BB2-432-Fix-JSON-SERIALIZATION-IN-SLSXTokenResponse
  apps/logging/tests/audit_logger_schemas.py
  apps/logging/tests/test_audit_loggers.py
  apps/mymedicare_cb/tests/mock_url_responses_slsx.py
  docker-compose.yml
  hhs_oauth_server/request_logging.py
Labels: bug

#922 BB2-634 New release script
  ops/build_autoincrement_release.sh
  ops/build_release.sh
  ops/github_release.py
Labels: enhancement

#916 [ BB2-22 ] Adding the pre-commit package and using it to run flake8
  .pre-commit-config.yaml
  docker-compose/readme.md
Labels: low
