Repository CMSgov/bluebutton-web-server, pull requests merged in 2021-06, with the labels that each got.

#927 BB2-653-Create-V2-User-Apps-View-in-Admin-BB2-TOOLS
  apps/bb2_tools/admin.py
  apps/bb2_tools/models.py
Labels: Medium

#928 BB2-651-Create-V2-Activities-Splunk-Dashboard
  splunk/v2_activities_dashboard.xml
Labels: low

#933 [ BB2-431 ] Adding a 5 second timeout to the external healthcheck endpoints
  apps/health/checks.py
  apps/mymedicare_cb/authorization.py
Labels: Medium

#926 BB2-652-Fix-AdminBB2-Tools-Splunkboards-links
  hhs_oauth_server/settings/base.py
Labels: Medium, bug

#930 [ BB2-610 ] disable bearer token
  apps/accounts/tests/test_api.py
  apps/capabilities/permissions.py
  apps/capabilities/tests.py
  apps/fhir/bluebutton/authentication.py
  apps/fhir/bluebutton/tests/test_read_and_search.py
Labels: Medium

#931 BB2-661-Add-Logging-for-V2-flag-blocked-fhir-requests
  apps/accounts/views/oauth2_profile.py
  apps/fhir/bluebutton/loggers.py
  apps/fhir/bluebutton/views/generic.py
  apps/logging/loggers.py
Labels: Medium

#939 BB2-584: DASG metrics add application state logging
  apps/logging/loggers.py
  apps/logging/tests/audit_logger_schemas.py
  apps/logging/tests/test_loggers_management_command.py
  apps/test.py
Labels: Medium, enhancement

#938 [ BB2-613 ] Use a fixed sign up link instead since you can only sign up on sandbox
  apps/home/templates/index.html
Labels: Medium

#937 [ BB2-600 ] Check for crosswalk before logging
  apps/logging/signals.py
Labels: Medium
