Repository CMSgov/bluebutton-web-server, pull requests merged in 2021-07, with the labels that each got.

#944 [ BB2-691 ] Unified Logging Solution
  apps/logging/request_logger.py
  apps/logging/tests/test_audit_loggers.py
  apps/mymedicare_cb/models.py
  hhs_oauth_server/request_logging.py
Labels: Medium

#945 BB2-637-Post-migrations-squash-cleanup
  apps/accounts/management/commands/create_admin_groups.py
  apps/accounts/migrations/0002_auto_20210624_1454.py
  apps/accounts/models.py
  apps/bb2_tools/migrations/0002_v2user.py
  apps/fhir/bluebutton/migrations/0002_remove_resourcerouter_fld_20210624_0826.py
  apps/fhir/server/migrations/0002_deprecate_resourcerouter_20210624_1454.py
  hhs_oauth_server/settings/base.py
  runtests.py
Labels: Medium, Migration Required

#947 BB2-717-Separate-BFD-SLS-healthcheck-into-specific-EPs
  apps/health/checks.py
  apps/health/urls.py
  apps/health/views.py
  apps/integration_tests/integration_test_fhir_resources.py
Labels: Medium

#932 BB2-545-Create-Selenium-Tests
  Dockerfile.selenium
  apps/integration_tests/common_utils.py
  apps/integration_tests/integration_test_fhir_resources.py
  apps/integration_tests/selenium_cases.py
  apps/integration_tests/selenium_tests.py
  docker-compose.selenium.yml
  docker-compose.yml
  docker-compose/bluebutton_server_start.sh
  docker-compose/readme.md
  docker-compose/run_integration_tests_local_keybase.sh
  docker-compose/run_selenium_tests_local_keybase.sh
  runtests.py
  templates/design_system/authorize_v2.html
Labels: Medium

#948 [ BB2-692 ] Creating openapi spec
  openapi.yaml
Labels: Medium

#951 BB2-545-Selenium-Tests-CertStore-Path-Mapping
  Dockerfile.selenium
  docker-compose.selenium.yml
  docker-compose/run_selenium_tests_local_keybase.sh
Labels: High, bug

#943 BB2-612: Allow MBI/HICN Updates with FHIR_ID Matching
  apps/bb2_tools/migrations/0002_v2user.py
  apps/fhir/bluebutton/admin.py
  apps/fhir/bluebutton/migrations/0003_archivedcrosswalk.py
  apps/fhir/bluebutton/models.py
  apps/fhir/bluebutton/tests/test_models.py
  apps/logging/tests/audit_logger_schemas.py
  apps/mymedicare_cb/loggers.py
  apps/mymedicare_cb/models.py
  apps/mymedicare_cb/tests/mock_url_responses_slsx.py
  apps/mymedicare_cb/tests/test_callback_slsx.py
  apps/mymedicare_cb/views.py
Labels: High, Migration Required, enhancement
